[tool.poetry]
name = "team2"
version = "0.1.0"
description = ""
authors = ["kimjiyong1022 <wldyd369@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
