# Generated by Django 5.2.3 on 2025-06-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=20)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "bank_code",
                    models.CharField(
                        choices=[
                            ("KAKAO", "카카오뱅크"),
                            ("NH", "농협은행"),
                            ("IBK", "IBK 기업은행"),
                            ("KB", "<국민은행>"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CHECKING", "입출금통장"),
                            ("MINUS", "마이너스 통장"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("deposit", "입금"), ("withdrawal", "출금")],
                        max_length=10,
                    ),
                ),
                (
                    "transaction_method",
                    models.CharField(
                        choices=[
                            ("card", "카드 결제"),
                            ("automatic_transfer", "자동이체"),
                            ("cash_deposit", "현금 입금"),
                            ("cash_withdrawal", "현금 출금"),
                            ("account_deposit", "계좌 입금"),
                            ("account_withdrawal", "계좌 출금"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
